// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import http "net/http"

import mock "github.com/stretchr/testify/mock"

// ApiHandlerInterface is an autogenerated mock type for the ApiHandlerInterface type
type ApiHandlerInterface struct {
	mock.Mock
}

// GetPath provides a mock function with given fields:
func (_m *ApiHandlerInterface) GetPath() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRequestType provides a mock function with given fields:
func (_m *ApiHandlerInterface) GetRequestType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Handle provides a mock function with given fields: w, r
func (_m *ApiHandlerInterface) Handle(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}
