// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import mux "github.com/gorilla/mux"

// ApiHandlerInterface is an autogenerated mock type for the ApiHandlerInterface type
type ApiHandlerInterface struct {
	mock.Mock
}

// AddHandlerToRouter provides a mock function with given fields: r
func (_m *ApiHandlerInterface) AddHandlerToRouter(r *mux.Router) {
	_m.Called(r)
}
