// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// ConsumerInterface is an autogenerated mock type for the ConsumerInterface type
type ConsumerInterface struct {
	mock.Mock
}

// InitializeConsumer provides a mock function with given fields:
func (_m *ConsumerInterface) InitializeConsumer() {
	_m.Called()
}
