// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ControllerInterface is an autogenerated mock type for the ControllerInterface type
type ControllerInterface struct {
	mock.Mock
}

// InitializeEndpoint provides a mock function with given fields:
func (_m *ControllerInterface) InitializeEndpoint() {
	_m.Called()
}
