// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// EurekaClientInterface is an autogenerated mock type for the EurekaClientInterface type
type EurekaClientInterface struct {
	mock.Mock
}

// InitializeEurekaConnection provides a mock function with given fields:
func (_m *EurekaClientInterface) InitializeEurekaConnection() {
	_m.Called()
}
