// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// PublisherInterface is an autogenerated mock type for the PublisherInterface type
type PublisherInterface struct {
	mock.Mock
}

// InitializePublisher provides a mock function with given fields:
func (_m *PublisherInterface) InitializePublisher() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PublishMessage provides a mock function with given fields: exchangeName, routingKey, payload
func (_m *PublisherInterface) PublishMessage(exchangeName string, routingKey string, payload interface{}) error {
	ret := _m.Called(exchangeName, routingKey, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(exchangeName, routingKey, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopPublisher provides a mock function with given fields:
func (_m *PublisherInterface) StopPublisher() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
