// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import amqp "github.com/streadway/amqp"

import mock "github.com/stretchr/testify/mock"

// RabbitHandlerInterface is an autogenerated mock type for the RabbitHandlerInterface type
type RabbitHandlerInterface struct {
	mock.Mock
}

// Handle provides a mock function with given fields: msg
func (_m *RabbitHandlerInterface) Handle(msg amqp.Delivery) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(amqp.Delivery) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
