version: '3'
services:
  discoveryservice:
    image: aista/eureka
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  gmapsadapter:
    depends_on:
      - discoveryservice
    image: aista/gmaps-adapter:local
    ports:
      - "8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice

  calculationservice:
    depends_on:
      - discoveryservice
    image: aista/calculation-service:local
    ports:
      - "8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice