version: '3'

services:

  discoveryservice:
    image: aista/eureka
    container_name: discoveryservice
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  calculationservice:
    image: aista/calculation-service
    container_name: calculationservice
    depends_on:
      - discoveryservice
      - rabbitmq
    ports:
      - "8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  gmapsadapter:
    image: aista/gmaps-adapter
    container_name: gmapsadapter
    depends_on:
      - discoveryservice
      - rabbitmq
    ports:
      - "8080"
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice

  notificationservice:
    image: aista/notification-service
    container_name: notificationservice
    command: notification-service
    depends_on:
      - discoveryservice
      - rabbitmq
    ports:
      - "32700:32700"
    environment:
      - RABBIT_HOST=rabbitmq
      - EUREKA_SERVER=discoveryservice

  mongo:
    image: 'mongo:3.4.1'
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'

volumes:
  mongo: