version: '3'  
services:
  discovery-service:
    image: aista/eureka
    ports:
      - "8761:8761"
  gmaps-adapter:
    depends_on:
      - discovery-service
    image: aista/gmaps-adapter
    ports:
      - "8080"
    environment:
      - EUREKA_SERVER=discovery-service
  calculation-service:
    depends_on:
      - discovery-service
    build: .
    command: ["go", "run", "main.go"]
    ports:
      - "8080"
    environment:
      - EUREKA_SERVER=discovery-service