version: '3'  
services:
  discoveryservice:
    image: aista/eureka
    ports:
      - "8761:8761"
  gmapsadapter:
    depends_on:
      - discoveryservice
    image: aista/gmaps-adapter
    ports:
      - "8080"
    environment:
      - EUREKA_SERVER=discoveryservice
  calculationservice:
    depends_on:
      - discoveryservice
    image: aista/calculation-service
    command: ["go", "run", "main.go"]
    ports:
      - "8080"
    environment:
      - EUREKA_SERVER=discoveryservice