version: '3'  
services:
  discovery-service:
    image: springcloud/eureka
    ports:
      - 8761:8761
  gmaps-adapter:
    image: aista/gmaps-adapter
    ports:
      - "8080"
  calculation-service:
    depends_on:
      - gmaps-adapter
    build: .
    command: ["go", "run", "main.go"]
    ports:
      - "8000"

